"""Broker protocol — structural typing contract for all broker implementations."""

from __future__ import annotations

from collections.abc import AsyncGenerator
from typing import Any, Protocol


class BrokerProtocol(Protocol):
    """Protocol (structural typing) for all broker adapters.

    Market-data and order-routing operations that every real or simulated
    broker must satisfy.  Duck-typed so that mocks and third-party wrappers
    can implement the subset they need without forced inheritance.
    """

    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def is_connected(self) -> bool: ...
    async def health(self) -> dict[str, Any]: ...

    # -- Order lifecycle ---------------------------------------------------
    async def submit_order(self, order: Any) -> str: ...
    async def cancel_order(self, broker_order_id: str) -> bool: ...
    async def amend_order(self, broker_order_id: str, **changes: Any) -> bool: ...
    async def order_status(self, broker_order_id: str) -> Any: ...

    # -- Position & streaming ----------------------------------------------
    async def positions(self) -> list[Any]: ...
    async def stream_orders(self) -> AsyncGenerator[Any, None]: ...
    async def stream_positions(self) -> AsyncGenerator[Any, None]: ...
