"""Strategy evolution orchestrator — sandbox gates + backtest + fitness scoring.

Pipeline for a candidate strategy:
  Source code → Gate 1 (AST audit) → Gate 2 (subprocess isolation)
  → Gate 3 (protocol check) → Backtest → Fitness score → Promote/discard

Inspired by Inalpha's strategy evolution (E1) with 3 sandbox gates,
multi-objective fitness, and baseline comparison.

Each candidate is versioned and its lineage is recorded so the system
can learn which mutations produce better strategies over time.
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from typing import Any

import numpy as np
import polars as pl

from genetics.gates.ast_audit import AuditResult, audit_source
from genetics.gates.protocol_check import ProtocolResult, check_protocol
from genetics.gates.subprocess_isolation import SubprocessResult, run_isolation

logger = logging.getLogger("oracle.genetics.evolution")


# ── Strategy template ────────────────────────────────────────────────

_STRATEGY_TEMPLATE = '''\
"""Auto-generated strategy: {name}"""

import polars as pl
import numpy as np


class {name}:
    """Strategy generated by evolution pipeline.

    Creates a long signal (1) or flat (0) for each bar.
    """

    def __init__(self{params_sig}) -> None:
{params_body}

    def compute(self, data: pl.DataFrame) -> pl.Series:
        close = data["close"]
{compute_body}
        return signal
'''


def make_strategy_source(
    name: str, compute_body: str, params: dict[str, tuple[str, Any]] | None = None
) -> str:
    """Build runnable Python source from a strategy name + compute body.

    Args:
        name: Class name (CamelCase).
        compute_body: Indented Python code for the compute() method body.
            Must assign to ``signal`` variable at the end.
        params: Dict of param_name → (type_str, default_value).
            E.g. ``{"period": ("int", 14), "threshold": ("float", 0.02)}``.

    Returns:
        Complete Python source string.
    """
    params = params or {}
    if params:
        sig = ", " + ", ".join(f"{n}: {t} = {v}" for n, (t, v) in params.items())
        body = "\n".join(f"        self.{n} = {n}" for n in params)
    else:
        sig = ""
        body = "        pass"
    return _STRATEGY_TEMPLATE.format(
        name=name, params_sig=sig, params_body=body, compute_body=compute_body
    )


# ── Sandbox pipeline results ─────────────────────────────────────────


@dataclass
class EvolutionResult:
    """Result of running a candidate through the evolution pipeline."""

    passed: bool = False
    stage: str = "init"  # ast_audit | subprocess | protocol | backtest | fitness
    class_name: str | None = None
    source: str = ""
    ast_audit: AuditResult | None = None
    subprocess: SubprocessResult | None = None
    protocol: ProtocolResult | None = None
    fitness: FitnessScore | None = None
    errors: list[str] = field(default_factory=list)
    duration_s: float = 0.0


@dataclass
class FitnessScore:
    """Multi-objective fitness score for a candidate strategy.

    Higher = better. Combines multiple metrics to prevent gaming.
    """

    sharpe: float = 0.0
    calmar_ratio: float = 0.0
    max_drawdown_pct: float = 100.0
    win_rate: float = 0.0
    total_return_pct: float = 0.0
    turnover: float = 0.0  # higher = more trades = higher costs
    fitness: float = 0.0  # composite score

    def compute_fitness(self) -> float:
        """Compute composite fitness: Sharpe + Calmar − turnover − DD penalty."""
        score = 0.0
        if self.sharpe > 0:
            score += min(2.0, self.sharpe) * 0.4
        if self.calmar_ratio > 0:
            score += min(2.0, self.calmar_ratio) * 0.3
        # Penalise drawdown
        dd_penalty = min(1.0, self.max_drawdown_pct / 10.0)
        score -= dd_penalty * 0.2
        # Penalise excessive turnover
        score -= min(0.5, self.turnover) * 0.1
        # Win rate bonus
        if self.win_rate > 0.5:
            score += (self.win_rate - 0.5) * 0.2
        self.fitness = round(max(0.0, score), 4)
        return self.fitness


# ── Quick backtest for candidate evaluation ──────────────────────────

_DEFAULT_CAPITAL = 100_000.0


def _quick_backtest(signal: np.ndarray, close: np.ndarray) -> FitnessScore:
    """Run a minimal backtest from signal + close arrays.

    Uses simple MTM accounting. Position is 1 contract MES ($5/pt).
    """
    if len(signal) < 20 or len(close) < 20:
        return FitnessScore()

    point_value = 5.0  # MES
    position = 0.0
    entry_price = 0.0
    equity = _DEFAULT_CAPITAL
    equity_curve = [equity]
    trades = 0

    for i in range(1, len(signal)):
        raw = signal[i]
        if raw is None or (isinstance(raw, float) and np.isnan(raw)):
            continue
        sig = int(raw)
        price = float(close[i])

        if sig != position:
            # Close existing position
            if position != 0:
                pnl = (price - entry_price) * position * point_value
                equity += pnl
                trades += 1
            # Open new position
            if sig != 0:
                entry_price = price
                position = sig
            else:
                position = 0.0

        equity_curve.append(equity)

    # Compute metrics
    equity_arr = np.array(equity_curve)
    returns = np.diff(equity_arr)
    if len(returns) < 2:
        return FitnessScore()

    total_return_pct = (equity_arr[-1] / _DEFAULT_CAPITAL - 1) * 100
    sharpe = float(np.mean(returns) / (np.std(returns) + 1e-9) * np.sqrt(252))
    peak = np.maximum.accumulate(equity_arr)
    dd = (equity_arr - peak) / peak * 100
    max_dd = float(abs(np.min(dd)))
    win_rate = float(np.sum(returns > 0) / max(1, len(returns)))
    calmar = float(sharpe / (max_dd / 100 + 1e-9)) if max_dd > 0 else 0.0
    turnover = trades / max(1, len(signal))

    score = FitnessScore(
        sharpe=round(sharpe, 4),
        calmar_ratio=round(calmar, 4),
        max_drawdown_pct=round(max_dd, 4),
        win_rate=round(win_rate, 4),
        total_return_pct=round(total_return_pct, 4),
        turnover=round(turnover, 4),
    )
    score.compute_fitness()
    return score


# ── Main evolution pipeline ──────────────────────────────────────────


def run_pipeline(source: str, close_prices: np.ndarray | None = None) -> EvolutionResult:
    """Run the full strategy evolution pipeline on a candidate.

    Args:
        source: Python source code of the candidate strategy.
        close_prices: Optional close price array for backtest.
            If None, uses random data for gate checks only.

    Returns:
        EvolutionResult with full pipeline trace.
    """
    t0 = time.monotonic()
    result = EvolutionResult(source=source)

    # ── Gate 1: AST audit ────────────────────────────────────────────
    result.stage = "ast_audit"
    result.ast_audit = audit_source(source)
    if not result.ast_audit.passed:
        result.errors = result.ast_audit.errors
        result.duration_s = round(time.monotonic() - t0, 2)
        return result
    result.class_name = result.ast_audit.class_name

    # ── Gate 2: Subprocess isolation ─────────────────────────────────
    result.stage = "subprocess"
    result.subprocess = run_isolation(source)
    if not result.subprocess.passed:
        result.errors = [result.subprocess.error or "Subprocess isolation failed"]
        result.duration_s = round(time.monotonic() - t0, 2)
        return result

    # ── Gate 3: Protocol check ───────────────────────────────────────
    result.stage = "protocol"
    result.protocol = check_protocol(source, class_name=result.class_name)
    if not result.protocol.passed:
        result.errors = result.protocol.errors or ["Protocol check failed"]
        result.duration_s = round(time.monotonic() - t0, 2)
        return result

    # ── Quick backtest ───────────────────────────────────────────────
    result.stage = "backtest"
    if close_prices is not None and len(close_prices) >= 50:
        # Load the candidate class and run compute
        try:
            import importlib.util
            import tempfile
            from pathlib import Path

            with tempfile.NamedTemporaryFile(
                mode="w", suffix=".py", delete=False, prefix="evo_", encoding="utf-8"
            ) as f:
                f.write(source)
                tmp = f.name

            spec = importlib.util.spec_from_file_location("_evo_candidate", tmp)
            if spec and spec.loader:
                mod = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(mod)
                strategy_cls = getattr(mod, result.class_name) if result.class_name else None
                if strategy_cls:
                    instance = strategy_cls()
                    n = len(close_prices)
                    data = pl.DataFrame(
                        {
                            "open": close_prices,
                            "high": close_prices * 1.01,
                            "low": close_prices * 0.99,
                            "close": close_prices,
                            "volume": np.ones(n) * 1000,
                        }
                    )
                    signal = instance.compute(data)
                    fitness = _quick_backtest(signal.to_numpy().astype(float), close_prices)
                    result.fitness = fitness
                    result.stage = "fitness"
            Path(tmp).unlink(missing_ok=True)
        except Exception as exc:
            result.errors.append(f"Backtest failed: {type(exc).__name__}: {exc}")
            result.duration_s = round(time.monotonic() - t0, 2)
            return result

    result.passed = True
    result.stage = "passed"
    result.duration_s = round(time.monotonic() - t0, 2)
    return result


# ── Report formatting ────────────────────────────────────────────────


def format_evolution_result(result: EvolutionResult) -> str:
    """Return a human-readable summary of the evolution pipeline result."""
    lines = [f"Strategy Evolution: {result.class_name or 'unknown'}", f"{'=' * 50}"]

    # Gate 1
    if result.ast_audit:
        status = "✅" if result.ast_audit.passed else "❌"
        lines.append(f"  Gate 1 (AST audit): {status}  ({result.ast_audit.node_count} nodes)")

    # Gate 2
    if result.subprocess:
        status = "✅" if result.subprocess.passed else "❌"
        excerpt = result.subprocess.stdout[:80] if result.subprocess.stdout else ""
        lines.append(f"  Gate 2 (subprocess): {status}  {excerpt}")

    # Gate 3
    if result.protocol:
        status = "✅" if result.protocol.passed else "❌"
        params = result.protocol.params or {}
        param_str = ", ".join(f"{k}={v}" for k, v in params.items())
        lines.append(f"  Gate 3 (protocol): {status}  params=[{param_str}]")

    # Fitness
    if result.fitness:
        f = result.fitness
        lines.append("  Backtest results:")
        lines.append(f"    Sharpe: {f.sharpe:>+7.3f}  Calmar: {f.calmar_ratio:>+7.3f}")
        lines.append(f"    Win rate: {f.win_rate:>5.1%}  Max DD: {f.max_drawdown_pct:>5.2f}%")
        lines.append(f"    Return: {f.total_return_pct:>+7.3f}%  Turnover: {f.turnover:.3f}")
        lines.append(f"    Fitness: {f.fitness:.4f}")

    # Errors
    if result.errors:
        lines.append(f"  Errors ({len(result.errors)}):")
        for err in result.errors:
            lines.append(f"    • {err}")

    lines.append(f"  Duration: {result.duration_s:.2f}s")
    lines.append(f"  Verdict: {'✅ PROMOTED' if result.passed else '❌ REJECTED'}")
    return "\n".join(lines) + "\n"


__all__ = [
    "EvolutionResult",
    "FitnessScore",
    "format_evolution_result",
    "make_strategy_source",
    "run_pipeline",
]
