"""Unit tests for ``analytics.macro.calendar`` (BL-724).

Covers:

* Loading the on-disk calendar — must contain >= 500 events.
* :func:`is_in_blackout_window` — returns True inside the window,
  False outside, and only fires for HIGH/MEDIUM events by default.
* Currency resolution — EURUSD reacts to both EUR and USD events;
  ES reacts only to USD events; GBPJPY reacts to both GBP and JPY.
* :func:`get_upcoming_events` — lookahead filter, currency filter,
  impact filter.
* :class:`MacroEvent` validation — timezone-naive inputs are coerced
  to UTC, currency codes are uppercased.
* :class:`MacroCalendar` filters and day lookup.
* :func:`compute_file_sha256` matches the ``file_sha256`` baked in
  the JSON header.

The calendar is regenerated by ``scripts/build_economic_calendar.py``
and is checked in — the tests assert against the on-disk artifact.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime, timedelta
from pathlib import Path

import pytest

from analytics.macro.calendar import (
    ASSET_CURRENCIES,
    DEFAULT_CALENDAR_PATH,
    SCHEMA_VERSION,
    ImpactLevel,
    MacroCalendar,
    MacroEvent,
    compute_file_sha256,
    get_upcoming_events,
    is_in_blackout_window,
)

# ─────────────────────────────────────────────────────────────────────
#  Calendar loading
# ─────────────────────────────────────────────────────────────────────


class TestCalendarLoading:
    def test_schema_version(self) -> None:
        assert SCHEMA_VERSION == "bl724-economic-calendar-v1"

    def test_default_path_exists(self) -> None:
        assert DEFAULT_CALENDAR_PATH.exists(), (
            f"Calendar missing at {DEFAULT_CALENDAR_PATH} — run scripts/build_economic_calendar.py"
        )

    def test_loads_at_least_500_events(self) -> None:
        cal = MacroCalendar.from_json()
        assert len(cal) >= 500, f"only {len(cal)} events, expected ≥500"

    def test_covers_2008_to_2026(self) -> None:
        cal = MacroCalendar.from_json()
        events = cal.events
        assert events[0].event_time_utc.year <= 2008
        assert events[-1].event_time_utc.year >= 2026

    def test_includes_key_event_families(self) -> None:
        cal = MacroCalendar.from_json()
        names = {ev.event_name for ev in cal.events}
        for required in (
            "FOMC Rate Decision",
            "ECB Rate Decision",
            "BOE Rate Decision",
            "Non-Farm Payrolls",
            "CPI m/m",
            "PPI m/m",
            "GDP Advance q/q",
            "Jackson Hole Symposium",
        ):
            assert required in names, f"missing event family: {required}"

    def test_event_ids_are_unique(self) -> None:
        cal = MacroCalendar.from_json()
        ids = [ev.event_id for ev in cal.events]
        assert len(ids) == len(set(ids))

    def test_each_event_has_source_sha256(self) -> None:
        cal = MacroCalendar.from_json()
        for ev in cal.events:
            assert ev.source_sha256, f"{ev.event_id} missing source_sha256"
            assert len(ev.source_sha256) == 64

    def test_empty_calendar_helper(self) -> None:
        assert len(MacroCalendar.empty()) == 0

    def test_from_json_missing_file_raises(self, tmp_path: Path) -> None:
        with pytest.raises(FileNotFoundError):
            MacroCalendar.from_json(tmp_path / "nope.json")

    def test_from_json_invalid_schema_raises(self, tmp_path: Path) -> None:
        bad = tmp_path / "bad.json"
        bad.write_text(json.dumps({"oops": []}))
        with pytest.raises(ValueError, match="missing 'events' key"):
            MacroCalendar.from_json(bad)

    def test_file_sha256_header_matches_disk(self) -> None:
        """The baked-in ``file_sha256`` matches the on-disk bytes."""
        # ``compute_file_sha256`` hashes the actual on-disk bytes; the
        # build script bakes a sha256 over the canonical (compact) form of
        # the document — they are derived from the same underlying dict so
        # the test asserts both end-to-end values match the helper.
        raw = json.loads(DEFAULT_CALENDAR_PATH.read_text())
        assert "file_sha256" in raw
        assert raw["file_sha256"] == compute_file_sha256(DEFAULT_CALENDAR_PATH)


# ─────────────────────────────────────────────────────────────────────
#  MacroEvent model
# ─────────────────────────────────────────────────────────────────────


class TestMacroEventModel:
    def test_naive_datetime_coerced_to_utc(self) -> None:
        ev = MacroEvent(
            event_id="x",
            event_name="x",
            currency="usd",
            event_time_utc=datetime(2024, 9, 18, 18, 0),
            impact_level=ImpactLevel.HIGH,
            source="s",
        )
        assert ev.event_time_utc.tzinfo is not None
        assert ev.event_time_utc.tzinfo == UTC
        assert ev.currency == "USD"

    def test_currency_normalized_upper(self) -> None:
        ev = MacroEvent(
            event_id="x",
            event_name="x",
            currency="eur",
            event_time_utc=datetime(2024, 1, 1, tzinfo=UTC),
            impact_level=ImpactLevel.MEDIUM,
            source="s",
        )
        assert ev.currency == "EUR"

    def test_event_is_frozen(self) -> None:
        ev = MacroEvent(
            event_id="x",
            event_name="x",
            currency="USD",
            event_time_utc=datetime(2024, 1, 1, tzinfo=UTC),
            impact_level=ImpactLevel.HIGH,
            source="s",
        )
        with pytest.raises(ValueError, match="frozen"):
            ev.event_name = "y"  # type: ignore[misc]


# ─────────────────────────────────────────────────────────────────────
#  Blackout window
# ─────────────────────────────────────────────────────────────────────


class TestBlackoutWindow:
    @pytest.fixture
    def cal(self) -> MacroCalendar:
        return MacroCalendar.from_json()

    def test_fomc_event_triggers_blackout_for_es(self, cal: MacroCalendar) -> None:
        # FOMC 2024-09-18 18:00 UTC is in the calendar.
        ts = datetime(2024, 9, 18, 18, 0, tzinfo=UTC)
        hit, eid = is_in_blackout_window(ts, "ES", cal)
        assert hit is True
        assert eid is not None
        assert "fomc" in eid.lower()

    def test_outside_window_returns_false(self, cal: MacroCalendar) -> None:
        # 30 minutes before FOMC is outside the default 5-minute window.
        ts = datetime(2024, 9, 18, 17, 20, tzinfo=UTC)
        hit, eid = is_in_blackout_window(ts, "ES", cal)
        assert hit is False
        assert eid is None

    def test_window_5min_before_event(self, cal: MacroCalendar) -> None:
        # 4 minutes before the FOMC = inside 5-min window.
        ts = datetime(2024, 9, 18, 17, 56, tzinfo=UTC)
        hit, _ = is_in_blackout_window(ts, "ES", cal)
        assert hit is True

    def test_window_5min_after_event(self, cal: MacroCalendar) -> None:
        # 4 minutes after the FOMC = inside 5-min window.
        ts = datetime(2024, 9, 18, 18, 4, tzinfo=UTC)
        hit, _ = is_in_blackout_window(ts, "ES", cal)
        assert hit is True

    def test_exact_event_time_is_in_window(self, cal: MacroCalendar) -> None:
        ts = datetime(2024, 9, 18, 18, 0, tzinfo=UTC)
        hit, _ = is_in_blackout_window(ts, "ES", cal)
        assert hit is True

    def test_naive_datetime_coerced_to_utc(self, cal: MacroCalendar) -> None:
        ts = datetime(2024, 9, 18, 18, 0)  # no tzinfo
        hit, _ = is_in_blackout_window(ts, "ES", cal)
        assert hit is True

    def test_eurusd_reacts_to_both_eur_and_usd(self, cal: MacroCalendar) -> None:
        # FOMC (USD) hits EURUSD
        ts_fomc = datetime(2024, 9, 18, 18, 0, tzinfo=UTC)
        hit_usd, eid_usd = is_in_blackout_window(ts_fomc, "EURUSD", cal)
        assert hit_usd is True
        assert "fomc" in eid_usd.lower()  # type: ignore[arg-type]

        # ECB (EUR) hits EURUSD
        ts_ecb = datetime(2024, 9, 12, 13, 45, tzinfo=UTC)
        hit_eur, eid_eur = is_in_blackout_window(ts_ecb, "EURUSD", cal)
        assert hit_eur is True
        assert "ecb" in eid_eur.lower()  # type: ignore[arg-type]

    def test_es_only_reacts_to_usd(self, cal: MacroCalendar) -> None:
        # ECB event should NOT affect ES.
        ts_ecb = datetime(2024, 9, 12, 13, 45, tzinfo=UTC)
        hit, eid = is_in_blackout_window(ts_ecb, "ES", cal)
        assert hit is False
        assert eid is None

    def test_ftse_reacts_to_gbp_not_usd(self, cal: MacroCalendar) -> None:
        # BOE 2024-09-19 12:00 UTC -> FTSE blackout
        ts_boe = datetime(2024, 9, 19, 12, 0, tzinfo=UTC)
        hit_gbp, eid_gbp = is_in_blackout_window(ts_boe, "FTSE", cal)
        assert hit_gbp is True
        assert "boe" in eid_gbp.lower()  # type: ignore[arg-type]

        # FOMC should NOT affect FTSE (FTSE is GBP-only).
        ts_fomc = datetime(2024, 9, 18, 18, 0, tzinfo=UTC)
        hit, _ = is_in_blackout_window(ts_fomc, "FTSE", cal)
        assert hit is False

    def test_gbpjpy_reacts_to_both_gbp_and_jpy(self, cal: MacroCalendar) -> None:
        ts_boe = datetime(2024, 9, 19, 12, 0, tzinfo=UTC)
        hit, _ = is_in_blackout_window(ts_boe, "GBPJPY", cal)
        assert hit is True
        ts_boj = datetime(2024, 9, 20, 3, 0, tzinfo=UTC)
        hit, _ = is_in_blackout_window(ts_boj, "GBPJPY", cal)
        assert hit is True

    def test_currency_argument_works(self, cal: MacroCalendar) -> None:
        # Passing "USD" directly instead of a symbol should work.
        ts = datetime(2024, 9, 18, 18, 0, tzinfo=UTC)
        hit, _ = is_in_blackout_window(ts, "USD", cal)
        assert hit is True

    def test_custom_window_widens_detection(self, cal: MacroCalendar) -> None:
        # 30 minutes before the FOMC — outside default 5m, inside 30m.
        ts = datetime(2024, 9, 18, 17, 30, tzinfo=UTC)
        hit_default, _ = is_in_blackout_window(ts, "ES", cal, window_before_m=5)
        assert hit_default is False
        hit_wide, _ = is_in_blackout_window(ts, "ES", cal, window_before_m=30)
        assert hit_wide is True

    def test_low_impact_does_not_trigger_by_default(self) -> None:
        """Synthetic LOW-impact event must NOT block by default."""
        ev = MacroEvent(
            event_id="low-test",
            event_name="LowImpact",
            currency="USD",
            event_time_utc=datetime(2024, 6, 1, 12, 0, tzinfo=UTC),
            impact_level=ImpactLevel.LOW,
            source="test",
        )
        cal2 = MacroCalendar([ev])
        ts = ev.event_time_utc
        hit, _ = is_in_blackout_window(ts, "ES", cal2)
        assert hit is False

    def test_medium_impact_uses_shorter_window(self) -> None:
        """MEDIUM events trigger with the scaled (2m) window, not the HIGH (5m)."""
        ev = MacroEvent(
            event_id="med-test",
            event_name="MedImpact",
            currency="USD",
            event_time_utc=datetime(2024, 6, 1, 12, 0, tzinfo=UTC),
            impact_level=ImpactLevel.MEDIUM,
            source="test",
        )
        cal2 = MacroCalendar([ev])
        # 1 minute before — inside the MEDIUM scaled window (2m).
        ts_inside = ev.event_time_utc - timedelta(minutes=1)
        hit, _ = is_in_blackout_window(ts_inside, "ES", cal2, window_before_m=5)
        assert hit is True
        # 4 minutes before — outside MEDIUM's 2m window even though inside HIGH's 5m.
        ts_outside = ev.event_time_utc - timedelta(minutes=4)
        hit, _ = is_in_blackout_window(ts_outside, "ES", cal2, window_before_m=5, window_after_m=5)
        assert hit is False

        # Sanity: same event at -4m DOES trigger if we widen the caller window.
        ts_wide = ev.event_time_utc - timedelta(minutes=4)
        hit, _ = is_in_blackout_window(ts_wide, "ES", cal2, window_before_m=10, window_after_m=10)
        # With caller window=10, MEDIUM scale = max(1, round(10*0.4)) = 4.
        # -4m sits exactly on the edge → inclusive → True.
        assert hit is True


# ─────────────────────────────────────────────────────────────────────
#  Upcoming events lookup
# ─────────────────────────────────────────────────────────────────────


class TestUpcomingEvents:
    @pytest.fixture
    def cal(self) -> MacroCalendar:
        return MacroCalendar.from_json()

    def test_lookahead_24h_finds_fomc(self, cal: MacroCalendar) -> None:
        # Look-ahead starting 1h before a known FOMC.
        ts = datetime(2024, 9, 18, 17, 0, tzinfo=UTC)
        events = get_upcoming_events(ts, cal, lookahead_hours=24)
        names = [e.event_name for e in events]
        assert "FOMC Rate Decision" in names

    def test_lookahead_excludes_past(self, cal: MacroCalendar) -> None:
        # Starting AFTER the FOMC — should NOT include it.
        ts = datetime(2024, 9, 18, 19, 0, tzinfo=UTC)
        events = get_upcoming_events(ts, cal, lookahead_hours=24)
        for ev in events:
            assert ev.event_time_utc >= ts

    def test_currency_filter(self, cal: MacroCalendar) -> None:
        ts = datetime(2024, 9, 1, 0, 0, tzinfo=UTC)
        events = get_upcoming_events(ts, cal, lookahead_hours=24 * 30, currency="EUR")
        assert events
        for ev in events:
            assert ev.currency == "EUR"

    def test_impact_filter(self, cal: MacroCalendar) -> None:
        ts = datetime(2024, 9, 1, 0, 0, tzinfo=UTC)
        high_only = get_upcoming_events(ts, cal, lookahead_hours=24 * 30, impact=ImpactLevel.HIGH)
        assert high_only
        for ev in high_only:
            assert ev.impact_level == ImpactLevel.HIGH

    def test_impact_tuple_filter(self, cal: MacroCalendar) -> None:
        ts = datetime(2024, 9, 1, 0, 0, tzinfo=UTC)
        events = get_upcoming_events(
            ts, cal, lookahead_hours=24 * 30, impact=(ImpactLevel.HIGH, ImpactLevel.MEDIUM)
        )
        assert events
        for ev in events:
            assert ev.impact_level in {ImpactLevel.HIGH, ImpactLevel.MEDIUM}

    def test_returns_empty_when_window_empty(self, cal: MacroCalendar) -> None:
        # Far-future window unlikely to contain anything.
        ts = datetime(2030, 1, 1, 0, 0, tzinfo=UTC)
        events = get_upcoming_events(ts, cal, lookahead_hours=1)
        assert events == []


# ─────────────────────────────────────────────────────────────────────
#  Calendar accessors + filters
# ─────────────────────────────────────────────────────────────────────


class TestCalendarFilters:
    @pytest.fixture
    def cal(self) -> MacroCalendar:
        return MacroCalendar.from_json()

    def test_filter_by_currency(self, cal: MacroCalendar) -> None:
        usd = cal.filter(currency="USD")
        eur = cal.filter(currency="EUR")
        assert usd and eur
        assert all(e.currency == "USD" for e in usd)
        assert all(e.currency == "EUR" for e in eur)
        assert len(usd) > len(eur)

    def test_filter_by_impact(self, cal: MacroCalendar) -> None:
        high = cal.filter(impact=ImpactLevel.HIGH)
        med = cal.filter(impact=ImpactLevel.MEDIUM)
        assert high
        assert all(e.impact_level == ImpactLevel.HIGH for e in high)
        assert all(e.impact_level == ImpactLevel.MEDIUM for e in med)

    def test_contains(self, cal: MacroCalendar) -> None:
        some_id = cal.events[0].event_id
        assert some_id in cal
        assert "does-not-exist" not in cal

    def test_get_returns_none_for_unknown(self, cal: MacroCalendar) -> None:
        assert cal.get("nope") is None
        assert cal.get(cal.events[0].event_id) is not None

    def test_events_on_specific_day(self, cal: MacroCalendar) -> None:
        # 2024-09-18 is a known FOMC day.
        evs = cal.events_on("2024-09-18")
        names = [e.event_name for e in evs]
        assert "FOMC Rate Decision" in names

    def test_events_on_returns_empty_for_unknown_day(self, cal: MacroCalendar) -> None:
        assert cal.events_on("1999-01-01") == []


# ─────────────────────────────────────────────────────────────────────
#  Asset → currency resolution
# ─────────────────────────────────────────────────────────────────────


class TestAssetCurrencies:
    def test_mapping_has_core_symbols(self) -> None:
        for sym in ("ES", "NQ", "EURUSD", "FTSE", "DAX", "BTCUSD"):
            assert sym in ASSET_CURRENCIES, f"{sym} not in ASSET_CURRENCIES"

    def test_eurusd_includes_both_legs(self) -> None:
        assert "EUR" in ASSET_CURRENCIES["EURUSD"]
        assert "USD" in ASSET_CURRENCIES["EURUSD"]

    def test_es_is_usd_only(self) -> None:
        assert ASSET_CURRENCIES["ES"] == ("USD",)
